#!/bin/bash

# このバージョンはDockerfileに書いてある内容
ruby_version=3.2.2
node_version=20
default_option="--force --database=postgresql"

echo "以下の内容でインストールします。"
echo "Rubyのバージョン: $ruby_version"
echo "Nodeのバージョン: $node_version"
echo "デフォルトオプション: $default_option"

read -p "この内容で次に進みますか？ (yes/no): " confirmation_default
if [ "$confirmation_default" != "yes" ]; then
  echo "バージョンを変える場合は、Dockerfile.tmpとscripts/setup_rails.shを編集してください。"
  echo "デフォルトオプションを変える場合は、scripts/setup_rails.shを編集してください。"
  echo "終了します。"
  exit 1
fi


echo "-------------------------------------------"
read -p "他に必要なオプションがあれば入力してください > " other_option
echo "以下のコマンドでRailsをインストールします。"
echo "rails new . $default_option $other_option"

read -p "この内容で次に進みますか？ (yes/no): " confirmation_other_option
if [ "$confirmation_other_option" != "yes" ]; then
  echo "終了します。"
  exit 1
fi

echo "-------------------------------------------"
echo "Dockerをビルドしています。"
echo "docker build -t rails-new-template -f Dockerfile.tmp ."
docker build -t rails-new-template -f Dockerfile.tmp .

echo "Railsをインストールしています。"
echo "docker run --rm -v ${PWD}:/app rails-new-template rails new . $default_option $other_option"
docker run --rm -v ${PWD}:/app rails-new-template rails new . $default_option $other_option


echo "-------------------------------------------"
echo "database.ymlを編集しています。"
cat scripts/templates/config/database.yml > config/database.yml

echo "Dockerfileを作成しています。"
mkdir -p docker
sed -e "s/RUBY_VERSION/$ruby_version/g" \
    -e "s/NODE_VERSION/$node_version/g" \
    scripts/templates/docker/Dockerfile.dev > docker/Dockerfile.dev


echo "-------------------------------------------"
cat scripts/templates/how_to_start.md
