FROM ruby:RUBY_VERSION

# 必要なライブラリのインストール
# nodeいらなければnode周りのインストールを削除する
RUN apt-get update -qq && \
  apt-get install -y libpq-dev curl gnupg2 && \
  curl -fsSL https://deb.nodesource.com/setup_NODE_VERSION.x | bash - && \
  apt-get install -y nodejs && \
  npm install -g npm@latest && npm install -g yarn && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Gemfileの追加とインストール
ADD Gemfile* /app/
RUN bundle install

# node入らなければ削除する
ADD package.json /app/
RUN yarn install --check-files

CMD ["rails", "server", "-b", "0.0.0.0"]
